services:
    sonata.admin.jamtype:
        class: App\JamStorageBundle\Admin\JamTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Type" }
        arguments:
            - ~
            - App\JamStorageBundle\Entity\JamType
            - ~
        calls:
            - [ setTranslationDomain, [AppJamStorageBundle]]