parameters:
#    app_jam_storage.example.class: App\JamStorageBundle\Example

services:
#    app_jam_storage.example:
#        class: %app_jam_storage.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
